// this file is auto generated, do not edit it directly
export interface AutoGeneratedConfigParams {
  cognitoDomain?: string;
  region?: string;
  cognitoUserPoolId?: string;
  cognitoUserPoolAppClientId?: string;
  apiUrl?: string;
}
export const autoGenConfigParams: AutoGeneratedConfigParams = {
  cognitoDomain: "reinforce2019-sdd412-2.auth.us-west-2.amazoncognito.com",
  region: "us-west-2",
  cognitoUserPoolId: "us-west-2_ICxtPK6Wh",
  cognitoUserPoolAppClientId: "5gaqiejeh8fer25rtbunknba8",
  apiUrl: "https://2nw00yoaf0.execute-api.us-west-2.amazonaws.com/prod/",
};
