// this file is auto generated, do not edit it directly
export interface AutoGeneratedConfigParams {
  cognitoDomain?: string;
  region?: string;
  cognitoUserPoolId?: string;
  cognitoUserPoolAppClientId?: string;
  apiUrl?: string;
}
export const autoGenConfigParams: AutoGeneratedConfigParams = {
  cognitoDomain: "reinforce2019-sdd412.auth.us-west-2.amazoncognito.com",
  region: "us-west-2",
  cognitoUserPoolId: "us-west-2_nqooCLPxs",
  cognitoUserPoolAppClientId: "1l4cfie7s2be68rkrdi4usi8lh",
  apiUrl: "https://6oqsoptvne.execute-api.us-west-2.amazonaws.com/prod/",
};
